# Generated by Django 5.2.15 on 2026-06-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('buy_currency', models.CharField(default='USD', max_length=10)),
                ('buy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('sell_currency', models.CharField(default='PKR', max_length=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ads_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('packaging', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marketplace_fee_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_fee_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('landing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('recommended_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
