# Generated by Django 5.2.15 on 2026-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('pro', 'Pro'), ('ecommerce', 'E-commerce')], default='trial', max_length=20),
        ),
    ]
