# Generated by Django 5.2.15 on 2026-06-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_schema',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
    ]
